version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/ylab_task2_db
      - SPRING_DATASOURCE_USERNAME=postgres2
      - SPRING_DATASOURCE_PASSWORD=postgres2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ylab_task2_db
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: postgres2